[program:go-server]
command=/app/bin/server
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/go-server.err.log
stdout_logfile=/var/log/go-server.out.log
environment=SERVER_PORT="4000",TZ="Asia/Jakarta"
user=nextjs

[program:nextjs]
command=node server.js
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/nextjs.err.log
stdout_logfile=/var/log/nextjs.out.log
environment=PORT="3000",NODE_ENV="production",TZ="Asia/Jakarta"
user=nextjs
